set_attribute -type boolean [get_pins ipad_RX7/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX6/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX5/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX4/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX3/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX2/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX1/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX0/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX7/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX6/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX5/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX4/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX3/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX2/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX1/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX0/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RECV_ERROR/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_IS_TX/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_IS_REC/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RECEIVED/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TX/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_TRANSMIT/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RX/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_RST/ANA] is_pad true
set_attribute -type boolean [get_pins ipad_CLK/ANA] is_pad true
